### ISSUE TITLE
Sequence panel: Full screen `nextCanvas()` issue

### ISSUE THREAD

**Issue by bulbil** [digirati-co-uk/iiif-canvas-panel#236] opened 2024-02-13 20:20 UTC
**Observed behavior**
When paging (`nextCanvas`/`previousCanvas`) in Fullscreen mode, the images are rendered out of the viewport.

**Expected behavior**
Firing a `nextCanvas()` updates the sequence and the HTML canvas element is updated to include the new items from the new sequence.

**Notes**
I believe there is some error in the calculation in where to place the new canvas and that there is an x offset being added unnecessarily.

(Not sure how related, but running in static mode, I noticed in `atlas/src/modules/static-renderer/static-renderer.ts` that       `element.style.transform = `translate(${x}px, ${y}px)`;` is incorrect. I was wondering if the calculations in the canvas renderer were similarly incorrect in the `paint` function.

**Comment by stephenwf** [comment] 2024-02-14 10:13
I _think_ this has been fixed in later Atlas versions. Worth re-testing with #238

**Comment by bulbil** [comment] 2024-02-14 19:21
I tested this both in our component and in canvas panel storybook but I am still seeing the issue.

I'm using this rudimentary story to test:

```
import { Story, Meta } from "@storybook/addon-docs";

<Meta title="Web components/Sequence Panel" />

<Story name="sequence panel test">
  <div>
    <sequence-panel
      id="sp"
      manifest-id="https://iiif.wellcomecollection.org/presentation/b18035723"
      render="static"
    >
      <div>
        <button
          onClick={() =>
            document.querySelector("sequence-panel").sequence.nextCanvas()
          }
        >
          +
        </button>
        <button
          onClick={() =>
            document
              .querySelector("sequence-panel")
              .webkitRequestFullScreen.call(
                document.querySelector("sequence-panel")
              )
          }
        >
          fullscreen
        </button>
      </div>
    </sequence-panel>
  </div>
</Story>
```

**Comment by bulbil** [comment] 2024-02-29 19:13
@stephenwf we were wondering if you'd had any thoughts about this. 

When we spoke last week you mentioned:
> I think there might be a function you'd need to call specifically after entering or exiting full screen. I'm not sure exactly which (Can explore more in GH)

We haven't had much luck with finding any function to call. I also wanted to make clear this happens whenever you resize, not just entering/leaving fullscreen.

This is of some urgency to our project.

**Comment by stephenwf** [comment] 2024-03-01 12:34
The PR for the fix is here: https://github.com/atlas-viewer/atlas/pull/33

I was able to replicate, and it was to do with how Atlas resizes based on the window.
```
rt.resize(
  viewport.current.width, 
  restProps.width, 
  viewport.current.height, 
  restProps.height
);
```

Which is essentially a `beforeWidth` + `afterWidth` and then it applies the changes. So it looks at where it _was_ and where it _is_ now and does a relative change. A completely valid way to have done this would to have just been something like: 

```
rt.setSize(newWidth, newHeight);
```

However Atlas keeps the focal point stable when resizing up and down. 

For example:
https://atlas-viewer-storybook.netlify.app/?path=/story/annotations--flexbox

This is a fluid layout, so if you zoom into an area that portion of the image will always be in view. If you make it small and then large - you will get back to the original position reliably. In comparison, if you resize OpenSeadragon it will gradually drift and zoom out. 

```
viewport = resize(viewport) + 'resize(viewport);
```

The problem was Atlas was being fed a stale value for the width. So it was told to resize up to 1200 and then resize up to 900 say. That has a relative size difference of 300. So the height was being increased by 300 each time you recalculated the size. Coming out of full screen feeds the correct values - but because all the calculations are relative, Atlas isn't able to recover. 

### Technical details

The problem is the `runtime.target` which is 5 numbers:
```
[0, x1, y1, x2, y2]
```

It's useful to think of this as an annotation, everything inside that annotation is what will be painted to the screen. So you "Annotate" the viewport essentially. The Aspect ratio and position are updated based on changes to the height/width of the container. 

However, if a resize that changes the aspect ratio is missed (or out of order with stale data):
```
rt.resize(
  100, 200, // width 100px -> 200px
  100, 100
);
```

Then doesn't skip the following resize:
```
rt.resize(
  200, 400, // width 200px -> 400px (x2)
  100, 200, // height 100px -> 200px (x2)
);
```

The difference will be calculated as 2x increase in both `x` and `y`, which will be applied relative to the existing size.

So it will take the previous `runtime.target` which is `0,0,100,100` and double it in size to:
```
[0, 0, 0, 200, 200]
```

Which is incorrect. As mentioned, the relative resizing is used to ensure that scaling up and down are stable and revisable. Since it's relative, if you keep passing it bad data, the viewport will drift more and more out of sync.

### Replication + debugging

Some extra APIs that might be useful for debugging in the future.

After replicating the bug, calling `runtime.goHome()` and then logging `runtime.getViewport()` I can see:
```
{x: 0, y: -2116.578857421875, width: 4822, height: 7605.157958984375}
```

Which instead should be:
```
{x: 0, y: 0, width: 4822, height: 2000 }
```
(the `height` is a guess, but around 2000).

The fix can be manually tested using:
```
runtime.target[2] = 0; // y1
runtime.target[4] = 2000; // y2/height
```

**Comment by stephenwf** [comment] 2024-03-01 12:39
PR and preview for testing is available at: https://github.com/digirati-co-uk/iiif-canvas-panel/pull/241

I've added a vite demo:
```
yarn vite
```

Available at localhost:3000/sequence-fs.html

**Comment by bulbil** [comment] 2024-03-01 22:19
@stephenwf thank you! that sounds right, I was watching the output of `rt.target` as I resized and noticed the increasing drift you mentioned.

One thing is that I'm now having issues installing the package from code sandbox. Could just be the service, seems like they might be experiencing some issues so I was unable to test. I'll keep my eye on it.

I noticed that in npm the package is already released at 1.0.58 but the repo package.json says 1.0.57

**Closed** 2024-03-01 22:21 UTC

**Comment by stephenwf** [comment] 2024-03-01 22:23
That's published on NPM as: `@digirati/canvas-panel-web-components@1.0.59`

**Comment by bulbil** [comment] 2024-03-01 22:32
👌🏽 perfect, thank you! works great. I knew it was something simple but I wasn't sure exactly where in the chain.

I appreciate the explanation, @danieltbrennan and I were both interested in a little more explanation of how this was all calculated.
